include:
  - docker-compose-tasks.yaml

services:
  postgres:
    image: postgres:15.0
    container_name: prefect-postgres
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - prefect_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    networks:
      - prefect_network

  prefect:
    image: prefecthq/prefect:3.3.4.dev2-python3.12-conda
    container_name: prefect-server
    restart: always
    volumes:
      - prefect:/root/.prefect
    command: ["prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_URL=http://localhost:4200
      - PREFECT_API_URL=http://localhost:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
      - PREFECT_API_DATABASE_ECHO=False
      - PREFECT_API_DATABASE_MIGRATE_ON_START=True
    ports:
      - 4200:4200
    networks:
      - prefect_network
    depends_on:
      - postgres

  flask-app:
    container_name: flask-app
    build:
      context: flow
      dockerfile: dockerfile
    volumes:
      - ./flow/source:/app
    user: 1000:1000
    ports:
      - "5000:5000"
    command: flask --app app run --debug --host=0.0.0.0
    depends_on:
      - prefect
    environment:
      - PREFECT_API_URL=http://prefect:4200/api
      - DB_URL=postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
    networks:
      - prefect_network

volumes:
  prefect_pgdata:
    driver: local
  prefect:
    driver: local

networks:
  prefect_network:
    # driver: bridge
